[gcp_service_account]
type = "service_account"
project_id = "project-ed-456518"
private_key_id = "c1176bc6afd773cfb22c5159adabe6b93a8c25e1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxP5fy5RkrKNVj
ECm04MWIRW54JwokrXoXgsGckjhWW8Kov8cJwA+6cjFVCDbOOityay5TVL8ojeLg
YLuPvKaISEr7pq0oeOhM+uPG1BeEp636jE+/sqRiTbtJpyE4kBLNC3U2wGltZgH+
vVjtVEvlBEUNLbi75SDiGEEwPwDsFxLU3FpsX1sH1LkBYDalGCqYdEh0D+qu5xbB
6kTdet9J1FyQmJphUX8PLfRufir0UfSbVjzgi8mih6mZQH5DtDgLfNlKj4APXod8
KTVTEnn3bMBFuJRqRZoDKW0ecfrn93fAx04vzNGjrBlR6BMg+gDy98HrzmELm0yV
qrU32lldAgMBAAECggEAH1HFm2+UaC4tsHS3beTmuorMN5JsZik6IOPjqrMinc3W
gmNqu+QSU2dgpK4QIxYfvbbHJ4XaxkN2AqBNHBuhUIT3rOpZgASHRazyaRxqcHAB
m7tFzzF1fwJNtPjBc8FvdQhQhKVwq5pCAX17NGp4A6Zivi6lTRwyWIkhIbGMS+sG
maLEeGr3WoKTFwYe1NdJODqS4Jh76mdiBolRAZFVsTlY/kQilypuMsezRcwu00dN
ZZkBWeuD43jeFTy9/ydpgcnPWyu99mdXbHWLM8Sap0itpD+jEHz6ML0Qv7NDvo1M
gtgZzFC75y30NUUsPv9SSDUdGUpWx8HgCe+yHlXuuQKBgQD5fr6t6bLCM2kVoXkZ
X9x87nqEntBs3c64u7YYel7IXqeB50fhpfFj/5EF3jrnvAICy9/EpHeTwVVst01I
O230O0Fm1pKqCAfqBEfTYIIaR32v4MykeQgFpoTRjU/xGum6WvKJ5snY/HWadxQc
uzfi/Czod6eA4nbRliKhj4j3uQKBgQC13qNfTI2Y9+zdm1TtM1L9Cv1Q9p2PcwOR
CA8Iic+UDqwIvuCiHDfsp5IN5OeF4h8QIFS1X0UkY1qxEpaj1/k7GsCJZQZbA2Qg
RZ3BQ6kpnIcovDbmPYS5xy+Gnt3L4mszG1RTAHOVQh30Q3d5P40Q6juMMuOWS34j
Z6jWan14xQKBgEz0EPAnYuGPZdwsH+P5s1I9ZEC/k13g1EAadcH7DH0U5OmmYn9w
5ZGIZDzBHL4ZOS2PoIdQiylhum175DRhUDrChBuqFzamn3pIs7a4z6g3YMb8uWIJ
irXjdJgF1CBzwp+eKazrKFrrE4L/M47hGA3E5j0Vmu6f6zId8rSORxrRAoGAMi/m
+3RfmrfH2Ht12yMPop52uvHjFuPRNyN3Ko8FBkFqPduWl4Wb9SVky4rATRTSJ5wU
ZByPMvRr4XNUuI/vydyfBwsmztTHu5QabWujccUtExOlPrH5P171AXwzjoDDvk2r
XmBAhQ7Cv1Yi0QW1gtZwakbcwOvCOjjvwYOPblUCgYAKg6Zzd6lTZSpiPJ6E0PYd
ergqSZPYdbU5ZfFrOucd+9ZWqcIDEwnxdbE7V/jBP29uXAauAUrfKq55wODnfdWI
gJD3aj1wHMEgEl/NOPszZRUl1rUPdFYUJ+JaVguq/fayk1pcPzrI8VfyqHZhoSTi
l1f99KGpIzdeR1u07CoSrw==
-----END PRIVATE KEY-----"""
client_email = "project-ed-admin@project-ed-456518.iam.gserviceaccount.com"
client_id = "114159962547785256157"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/project-ed-admin%40project-ed-456518.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
